/* 풋볼 프로젝트 유저 테이블 생성 */ 
CREATE TABLE FB_USER ( 
	FB_USER_ID INT(11) NOT NULL AUTO_INCREMENT COMMENT '유저 ID', 
	FB_USER_EMAIL VARCHAR(50) NOT NULL COMMENT '유저 이메일',
	FB_USER_PSWD VARCHAR(100) NOT NULL COMMENT '유저 비밀번호', 
	FB_USER_NICKNAME VARCHAR(100) NOT NULL COMMENT '유저 닉네임', 
	FB_USER_NAME VARCHAR(100) NOT NULL COMMENT '유저 이름', 
	FB_USER_BIRTH VARCHAR(10) COMMENT '유저 생년월일', 
	FB_USER_PHONE VARCHAR(11) COMMENT '유저 휴대폰번호', 
	FB_USER_ADDRESS VARCHAR(100) COMMENT '유저 주소', 
	FB_USER_AUTH VARCHAR(2) NOT NULL COMMENT '유저 권한', 
	FB_USER_DEL_YN VARCHAR(2) NOT NULL COMMENT '유저 삭제여부', 
	FB_USER_REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '유저 등록일', 
	FB_USER_MOD_DATE DATETIME DEFAULT NULL COMMENT '유저 수정일', 
	PRIMARY KEY (FB_USER_ID) 
) COMMENT '회원정보';

/*user 테이블 칼럼 조회*/
show columns from FB_USER;

/*자유게시판 테이블 생성*/
CREATE TABLE FREE_BOARD(
	FREE_BOARD_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '자유게시판 ID',
	FB_USER_ID INT(11) NOT NULL COMMENT '유저 ID',
	FREE_BOARD_AUTHOR VARCHAR(100) NOT NULL COMMENT '자유게시판 작성자',
	FREE_BOARD_TITLE VARCHAR(100) NOT NULL COMMENT '자유게시판 제목', 
	FREE_BOARD_TEXT VARCHAR(100) COMMENT '자유게시판 내용', 	
	FREE_BOARD_REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '자유게시판 작성시간', 
	FREE_BOARD_MOD_DATE DATETIME DEFAULT NULL COMMENT '자유게시판 수정시간', 
	FREE_BOARD_IMG_PATH VARCHAR(100) COMMENT '자유게시판 이미지', 
	FREE_BOARD_DEL_YN VARCHAR(2) NOT NULL COMMENT '자유게시판 삭제여부', 
	FOREIGN KEY(FB_USER_ID) REFERENCES FB_USER(FB_USER_ID)
) COMMENT '자유게시판';

/*자유게시판 테이블 칼럼 조회*/
show columns from FREE_BOARD;

/*자유게시판 댓글 테이블 생성*/
CREATE TABLE FREE_BOARD_COMMENT(
	FBC_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '자유게시판 댓글 ID',
	FREE_BOARD_ID INT(11) NOT NULL COMMENT '자유게시판 ID',
	FBC_AUTHOR VARCHAR(100) NOT NULL COMMENT '자유게시판 댓글 작성자', 
	FBC_TEXT VARCHAR(100) COMMENT '자유게시판 댓글 내용', 	
	FBC_REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '자유게시판 댓글 작성시간', 
	FBC_MOD_DATE DATETIME DEFAULT NULL COMMENT '자유게시판 댓글 수정시간', 
	FBC_DEL_YN VARCHAR(2) NOT NULL COMMENT '자유게시판 댓글 삭제여부', 
	FOREIGN KEY(FREE_BOARD_ID) REFERENCES FREE_BOARD(FREE_BOARD_ID)
) COMMENT '자유게시판 댓글';

/*자유게시판 댓글 테이블 칼럼 조회*/
SHOW COLUMNS FROM FREE_BOARD_COMMENT;

/*건의게시판 테이블 생성*/
CREATE TABLE SUGGESTION_BOARD(
	SUGGESTION_BOARD_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '건의게시판 ID',
	FB_USER_ID INT(11) NOT NULL COMMENT '유저 ID',
	SUGGESTION_BOARD_AUTHOR VARCHAR(100) NOT NULL COMMENT '건의게시판 작성자',
	SUGGESTION_BOARD_TITLE VARCHAR(100) NOT NULL COMMENT '건의게시판 제목', 
	SUGGESTION_BOARD_TEXT VARCHAR(100) COMMENT '건의게시판 내용', 	
	SUGGESTION_BOARD_REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '건의게시판 작성시간', 
	SUGGESTION_BOARD_MOD_DATE DATETIME DEFAULT NULL COMMENT '건의게시판 수정시간', 
	SUGGESTION_BOARD_IMG_PATH VARCHAR(100) COMMENT '건의게시판 이미지', 
	SUGGESTION_BOARD_DEL_YN VARCHAR(2) NOT NULL COMMENT '건의게시판 삭제여부', 
	FOREIGN KEY(FB_USER_ID) REFERENCES FB_USER(FB_USER_ID)
) COMMENT '건의게시판';

/*건의게시판 테이블 칼럼 조회*/
show columns from SUGGESTION_BOARD;

/*건의게시판 댓글 테이블 생성*/
CREATE TABLE SUGGESTION_BOARD_COMMENT(
	SBC_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '건의게시판 댓글 ID',
	SUGGESTION_BOARD_ID INT(11) NOT NULL COMMENT '건의게시판 ID',
	SBC_AUTHOR VARCHAR(100) NOT NULL COMMENT '건의게시판 댓글 작성자', 
	SBC_TEXT VARCHAR(100) COMMENT '건의게시판 댓글 내용', 	
	SBC_REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '건의게시판 댓글 작성시간', 
	SBC_MOD_DATE DATETIME DEFAULT NULL COMMENT '건의게시판 댓글 수정시간', 
	SBC_DEL_YN VARCHAR(2) NOT NULL COMMENT '건의게시판 댓글 삭제여부', 
	FOREIGN KEY(SUGGESTION_BOARD_ID) REFERENCES SUGGESTION_BOARD(SUGGESTION_BOARD_ID)
) COMMENT '건의게시판 댓글';

/*건의게시판 댓글 테이블 칼럼 조회*/
SHOW COLUMNS FROM SUGGESTION_BOARD_COMMENT;

/*투표 테이블 생성*/
CREATE TABLE VOTE(
	VOTE_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '투표 ID',
	VOTE_DATE DATETIME NOT NULL COMMENT '투표대상 날짜'
) COMMENT '투표';

/*투표 테이블 칼럼 조회*/
SHOW COLUMNS FROM VOTE;

/*참석 테이블 생성*/
CREATE TABLE ATTEND(
	ATTEND_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '참석 ID',
	VOTE_ID INT(11) NOT NULL COMMENT '투표 ID',
	FB_USER_ID INT(11) NOT NULL COMMENT '유저 ID', 
	ATTEND_STATUS VARCHAR(2) NOT NULL COMMENT '참석 상태', 
	FOREIGN KEY(VOTE_ID) REFERENCES VOTE(VOTE_ID),
	FOREIGN KEY(FB_USER_ID) REFERENCES FB_USER(FB_USER_ID)
) COMMENT '참석';

/*참석 테이블 칼럼 조회*/
SHOW COLUMNS FROM ATTEND ;

/*회비 테이블 생성*/
/*기존의 회비 테이블 삭제 후 생성*/
CREATE TABLE FEE(
	FEE_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '회비 ID',
	FB_USER_ID INT(11) NOT NULL COMMENT '유저 ID',
	FEE_MONTH INT(2) not null COMMENT '회비 납부 월',
	FOREIGN KEY(FB_USER_ID) REFERENCES FB_USER(FB_USER_ID)
) COMMENT '회비';

/*회비 테이블 칼럼 조회*/
show columns from FEE;

/*pk, fk 상관없이 해당데이터 삭제하고 싶을 때 0, 원복 1*/
set foreign_key_checks = ${value};

/*공지사항 테이블 생성*/
CREATE TABLE NOTICE(
	NOTICE_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '공지사항 ID',
	FB_USER_ID INT(11) NOT NULL COMMENT '유저 ID',
	NOTICE_AUTHOR VARCHAR(100) NOT NULL COMMENT '공지사항 작성자',
	NOTICE_TITLE VARCHAR(100) NOT NULL COMMENT '공지사항 제목', 
	NOTICE_TEXT VARCHAR(100) COMMENT '공지사항 내용', 	
	NOTICE_REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '공지사항 작성시간', 
	NOTICE_MOD_DATE DATETIME DEFAULT NULL COMMENT '공지사항 수정시간', 
	NOTICE_IMG_PATH VARCHAR(100) COMMENT '공지사항 이미지', 
	NOTICE_DEL_YN VARCHAR(2) NOT NULL COMMENT '공지사항 삭제여부', 
	FOREIGN KEY(FB_USER_ID) REFERENCES FB_USER(FB_USER_ID)
) COMMENT '공지사항';

/*공지사항 테이블 칼럼 조회*/
SHOW COLUMNS FROM NOTICE ;

/*멤버 테이블 생성*/
CREATE TABLE MEMBER ( 
	MEMBER_ID INT(11) NOT null PRIMARY KEY AUTO_INCREMENT COMMENT '멤버 ID',
	FB_USER_ID INT(11) NOT NULL COMMENT '유저 ID',  
	MEMBER_NAME VARCHAR(100) NOT NULL COMMENT '멤버 이름',
	MEMBER_DRIBBLE_ABILITY INT(2) COMMENT '멤버 드리블 능력', 
	MEMBER_PASSING_ABILITY INT(2) COMMENT '멤버 패스 능력', 
	MEMBER_DEFENDING_ABILITY INT(2) COMMENT '멤버 수비 능력', 
	MEMBER_STAMINA INT(2) COMMENT '멤버 체력', 
	MEMBER_FINISHING_ABILITY INT(2) COMMENT '멤버 골결정력', 
	FOREIGN KEY(FB_USER_ID) REFERENCES FB_USER(FB_USER_ID)
) COMMENT '멤버';

SHOW COLUMNS FROM MEMBER;

/*팀 테이블 생성*/
CREATE TABLE TEAM ( 
	TEAM_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '팀 ID',
	VOTE_ID INT(11) NOT NULL COMMENT '투표 ID',  
	TEAM_NAME VARCHAR(100) NOT NULL COMMENT '팀 이름',
	FOREIGN KEY(VOTE_ID) REFERENCES VOTE(VOTE_ID)
) COMMENT '팀';

SHOW COLUMNS FROM TEAM; 

/*팀 멤버 테이블 생성*/
CREATE TABLE TEAM_MEMBER ( 
	TEAM_MEMBER_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '팀 멤버 ID',
	TEAM_ID INT(11) NOT NULL COMMENT '팀 ID',
	MEMBER_ID INT(11) NOT NULL COMMENT '멤버 ID',
	FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
) COMMENT '팀 멤버';

SHOW COLUMNS FROM TEAM_MEMBER;
